# Generated by Django 5.1.3 on 2024-11-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['status'], name='email_manag_status_98dfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['scheduled_time'], name='email_manag_schedul_8ada71_idx'),
        ),
    ]
